spring:
  config:
    import: optional:file:.env[.properties]

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  datasource:
    url: ${DB_URL:${LOCAL_DB_URL:jdbc:mysql://localhost:3306/fitback?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}}
    username: ${DB_USER:${LOCAL_DB_USERNAME:root}}
    password: ${DB_PW:${LOCAL_DB_PASSWORD:}}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${LOCAL_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug


jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: 1800000       # 30분 (ms)
  refresh-token-expiration: 1209600000   # 14일 (ms)
