CREATE TABLE IF NOT EXISTS password_reset_token (
    member_id BIGINT NOT NULL,
    token_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    expires_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT PK_PASSWORD_RESET_TOKEN PRIMARY KEY (member_id),
    CONSTRAINT UK_PASSWORD_RESET_TOKEN_TOKEN_HASH UNIQUE (token_hash),
    CONSTRAINT FK_PASSWORD_RESET_TOKEN_MEMBER
        FOREIGN KEY (member_id)
        REFERENCES member (member_id)
        ON DELETE CASCADE,
    INDEX IDX_PASSWORD_RESET_TOKEN_EXPIRES_AT (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
