ALTER TABLE image DROP CHECK CK_IMAGE_STATUS;

ALTER TABLE image
    ADD CONSTRAINT CK_IMAGE_PURPOSE
        CHECK (purpose IN (
            'ANALYSIS_ORIGINAL', 'LOOKBOOK_ORIGINAL', 'LOOKBOOK_MATCHED',
            'PROFILE', 'ANALYSIS', 'LOOKBOOK'
        ));

ALTER TABLE image
    ADD CONSTRAINT CK_IMAGE_STATUS
        CHECK (status IN (
            'PENDING', 'PENDING_UPLOAD', 'READY', 'ACTIVE', 'DELETING',
            'DELETE_FAILED', 'DELETED', 'REJECTED'
        ));
